nombre = input("Ingrese el nombre: ")
telefono = input("Ingrese el teléfono: ")
correo = input("Ingrese el correo: ")
direccion = input("Ingrese la dirección: ")
print("Datos completos:")
print("Nombre:", nombre)
print("Teléfono:", telefono)
print("Correo:", correo)
print("Dirección:", direccion)